### ISSUE TITLE
Chord graph can't display properly

### ISSUE THREAD

**Issue by Jiannan28** [shahinrostami/chord#18]
Try to create chord with the below matrix value, but can't display properly:

matrix2 = [
    [156, 46, 1, 1, 3, 0, 24],
    [46, 565, 6, 2, 10, 3, 51],
    [1, 6, 15, 0, 1, 0,1],
    [1, 2, 0, 7, 0, 0, 1],
    [3, 10, 1, 0, 16, 2, 3],
    [0, 3, 0, 0, 2, 9, 1],
    [24, 51, 1, 1, 3, 1, 143],
]

<img width="1792" alt="error" src="https://user-images.githubusercontent.com/11832120/94778723-581cfe80-03f8-11eb-9047-47a0df8c9ee5.png">

**Comment by shahinrostami** [comment]
Thanks for raising this.

This package is primarily for visualising co-occurrence rather than a mix of co-occurrence and occurrence (the diagonal of the matrix). This exception is thrown when the diagonal values are proportionally larger than half the sum of the matrix.

Explanation aside, I've found a fix, and will be pushing an update soon!

**Comment by shahinrostami** [comment]
This bug has been fixed in Chord Pro:

<img width="716" alt="Screenshot 2020-10-03 at 23 52 42" src="https://user-images.githubusercontent.com/15690380/95003108-96224a00-05d3-11eb-9601-7c17a08bd345.png">

I will add this to the error handling update coming soon to both Chord Free.

**Comment by Jiannan28** [comment]
Thank you @shahinrostami . Adding the occurrence support will be super helpful.

**Comment by shahinrostami** [comment]
> Thank you @shahinrostami . Adding the occurrence support will be super helpful.

It's available now in Chord Pro!

**Comment by Jiannan28** [comment]
Thanks @shahinrostami . Could I know if that's will be also available in Chord free version on your roadmap?

**Comment by val-ismaili** [comment]
@shahinrostami is it possible to get labels for both ends of the occurences to show up? i.e. on the hover pop up between A and G, get it to show A to G occurence is X, and G to A occurence is Y ?

**Comment by shahinrostami** [comment]
> @shahinrostami is it possible to get labels for both ends of the occurences to show up? i.e. on the hover pop up between A and G, get it to show A to G occurence is X, and G to A occurence is Y ?

I've created a new issue from your comment @val-ismaili , check it out here https://github.com/shahinrostami/chord/issues/24#issue-746730826. I'll be working on it 👍

**Comment by akdeepak** [comment]
Hi @shahinrostami  ,
We are using the chord for co occurence relationship since it has a very good visual representation .
The problem we are facing is the labels are not fully shown in the display. 
could you please let us know how can we solve this issue,  since the labels are having larger words , so " wrap_labels = True"  hiding the complete label name
<img width="499" alt="python_chord" src="https://user-images.githubusercontent.com/19904559/101441838-05078080-3940-11eb-853f-fdde9c2735f2.PNG">

**Comment by polyra** [comment]
> Hi @shahinrostami ,
> We are using the chord for co occurence relationship since it has a very good visual representation .
> The problem we are facing is the labels are not fully shown in the display.
> could you please let us know how can we solve this issue, since the labels are having larger words , so " wrap_labels = True" hiding the complete label name

Hello @akdeepak - this is a closed issue about a different problem you're replying to! Are you a `chord pro` user?
