### ISSUE TITLE
Scaling option

### ISSUE THREAD

**Issue by ynskoroglu** [shahinrostami/chord#3]
Hello I am totally new to world of interactive graphs though I wanted implement this system to my laboratories dateset. I have small issue regarding readability. I want to host my results locally but the resulting HTML doesn't scale or minimize and it becomes divided. Zooming in or out in the browser also doesn't scale down the graph as well. Is it possible to deploy a solution for this problem which users with little to no JS knowledge could also implement.

As of current my results look like this:
![Untitled](https://user-images.githubusercontent.com/37922796/79048150-b45e4d00-7c23-11ea-8b7a-2e5f171ba7ae.png)

Result file is: 
[Network_Chord_m.zip](https://github.com/shahinrostami/chord/files/4464874/Network_Chord_m.zip)

**Comment by shahinrostami** [comment]
Hello @ynskoroglu 

I will add height and width as optional flags to the chord constructor, this should give you control over the output. In the meantime, for readability, if you make your browser window narrow you will see that the diagram is responsive and will shrink to fit. 

Once it's ready, I'll close this issue so that you are notified.

**Comment by ynskoroglu** [comment]
Thanks for swift response and small trick. Will follow the updates.

**Comment by shahinrostami** [comment]
You can update to `chord 0.0.8` (commit 2b62379fd349107c272e89abfbd5b42900ea9e8d) which has the optional flag `width`! I hope this addreses your issue.

**Comment by ynskoroglu** [comment]
This is perfectly working, thanks for the update.
