### ISSUE TITLE
package is no longer working

### ISSUE THREAD

**Issue by ringhilterra** [shahinrostami/chord#4]
As of this morning without changing any of the versioning, the package no longer works for me. I see an error in the console. Yesterday, the same exact notebook was working fine. (to_html() .html file results has the same error shown when trying to render the html file)

Did some of the html / js code the package is referencing change last night / this morning? Im surprised it stopped working when I didn't change any versions

I also tried updating to the latest version this morning and I still get the same error

![Screen Shot 2020-04-16 at 6 54 45 AM](https://user-images.githubusercontent.com/3506706/79464767-5927b400-7faf-11ea-874c-679c2cb210f2.png)

**Comment by ringhilterra** [comment]
ah, after updating to the latest version in pip and restarting the kernel, it is now working.

**Comment by shahinrostami** [comment]
Hi @ringhilterra, I'm glad that updating was an option and that it's working for you now! Part of what makes `chord` so easy to deploy in notebooks and on the web is, as you suggested, the loading of the external template. The issue you encountered this morning (I think) will have been from executing an earlier version of `chord`, which downloaded a new template that it wouldn't handle properly. 

The new version enables easy margin control which fixes some of the issues with the labels being clipped. If you check the README you can see some of the new default options too! 

Moving forward I will figure out some way to manage multiple template versions so that older versions do not break when there is an update.

All the best!

Shahin

**Comment by jcherry-risklens** [comment]
Interestingly I'm getting the exact same browser console error while in Jupyter Lab, with no chart rendered, and I'm running the current version of chord (0.3.0). Thoughts?

**Comment by shahinrostami** [comment]
Hello @jcherry-risklens - happy to check this out for you. Can you post a new issue and attach a minimal example (python notebook) that reproduces your error?
